create table if not exists
  public.provinces (
    id integer generated by default as identity primary key,
    lo text not null,
    en text not null,
    is_active bool default true
  );

create table if not exists
  public.districts (
    id integer generated by default as identity primary key,
    lo text not null,
    en text not null,
    is_active bool default true,
    prov_id integer references provinces (id)
  );

create table if not exists
  public.villages (
    id integer generated by default as identity primary key,
    lo text not null,
    en text not null,
    is_active bool default true,
    dist_id integer references districts (id)
  );